prioritize classes used by other classes first
E.g. BIMResourceProductivity is using ISODuration for it's collection prop quantity_consumed. And if we try to reregister BIMResourceProductivity before registering ISODuration, we'll get the error below.

TypeError: CollectionProperty(...): expected an RNA type, failed with:
RuntimeError: , missing bl_rna attribute from 'RNAMetaPropGroup' instance (may not be registered)

Error: Python: Traceback (most recent call last):
  File "\bbim_reload_addon.py", line 73, in execute
    n = self.reregister_modules_recursive(self.props.basename+'.'+self.props.module)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\bbim_reload_addon.py", line 54, in reregister_modules_recursive
    bpy.utils.register_class(cl)
ValueError: bpy_struct "BIMResourceProductivity" registration error: 'quantity_consumed' CollectionProperty could not register (see previous error)